[package]
name = "multichat-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
tokio = { version = "1.6.1", features = ["macros", "rt-multi-thread", "fs", "net", "sync"] }
toml = "0.5.8"
serde = { version = "1.0.126", features = ["derive"] }
log = "0.4.14"
env_logger = "0.8.4"
async-trait = "0.1.50"
tokio-native-tls = "0.3.0"

multichat-proto = { path = "../multichat-proto" }
slab = "0.4.3"
arrayvec = "0.7.1"
